include(checks)

function(jgui_target target)
	if(MSVC)
		target_compile_options(${target} PRIVATE /W4 /WX)
	else()
		target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror)
	endif()
	check(${target})
endfunction()
