name: Checks
on: [push]
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3 wx3.0-headers libwxgtk3.0-gtk3-dev libclang1 libclang-12-dev lcov valgrind

      - name: Run Tests
        run: |
          cmake -B .build
          make -C .build
          ctest --test-dir .build -T memcheck

      - name: Generate Coverage Info
        if: always()
        run: |
          lcov -c -i -d .build/src -o zero_coverage.info
          lcov -c -d .build/src -o test_coverage.info
          lcov -a zero_coverage.info -a test_coverage.info -o coverage.info

      - name: Publish Coverage
        if: always()
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}

  include-what-you-use:
    name: Include What You Use
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3 iwyu libclang-9-dev cmake

      - name: Run Include What You Use
        run: |
          cmake -B .build
          make -C .build iwyu

  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3 cmake clang-format

      - name: Run clang-format
        run: |
          cmake -B .build
          make -C .build clang-format
 
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3 cmake clang-tidy

      - name: Run clang-format
        run: |
          cmake -B .build
          make -C .build clang-tidy

  cppcheck:
    name: CPPCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up Dependencies
        run: |
          sudo apt update
          sudo apt-get install -y python3 cmake cppcheck

      - name: Run cppcheck
        run: |
          cmake -B .build
          make -C .build cppcheck

